AWSTemplateFormatVersion: '2010-09-09'
Description: Common API Gateway for Public API and Strategic Integrations API

Parameters:
  Namespace:
    Type: String
    Description: Name given to a environment
  EnvironmentType:
    Type: String
    Description: type of the environment
    Default: nonproduction
    AllowedValues:
      - production
      - nonproduction
  ApiRateLimit:
    Type: String
    Description: Number of requests allowed per second per api key
    Default: 100
  ApiBurstLimit:
    Type: String
    Description: Number of concurrent request allowed
    Default: 200
  ApiVersion:
    Type: String
    Description: API Version
    Default: v1
Resources:
  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Description: POC API Gateway
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Ref AWS::StackName
      Tags:
        - Key: "Name"
          Value: !Ref AWS::StackName
        - Key: "EnvironmentType"
          Value: !Ref EnvironmentType

  #### AUTHORIZER ####
  CognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      IdentitySource: method.request.header.Authorization
      Name: !Sub ${Namespace}-cognito-authoirzer
      ProviderARNs:
        - Fn::ImportValue: !Join [ ':', [ !Ref Namespace,'CognitoUserPoolArn']]
      RestApiId: !Ref APIGateway
      Type: COGNITO_USER_POOLS

  #### API GATEWAY STAGES ####

  LatestStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref APIDeployment
      RestApiId: !Ref APIGateway
      StageName: LATEST
      TracingEnabled: true

  APIDeployment:
    DependsOn:
      - HelloWorldAPI
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref APIGateway

  ApiVersionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGateway
      ParentId: !GetAtt APIGateway.RootResourceId
      PathPart: !Ref ApiVersion

  ### TALENT LMS CALLBACK API STACKS ####
  HelloWorldAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: apis/hello-world-v1.yaml
      Parameters:
        APIGatewayID: !Ref APIGateway
        RootResourceId: !GetAtt APIGateway.RootResourceId
        AuthorizerId: !Ref CognitoAuthorizer
        Namespace: !Ref Namespace
        ApiVersionResource: !Ref ApiVersionResource

  ### TALENT LMS CALLBACK API STACKS ####
  HappyWorldAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: apis/happy-world-v1.yaml
      Parameters:
        APIGatewayID: !Ref APIGateway
        RootResourceId: !GetAtt APIGateway.RootResourceId
        AuthorizerId: !Ref CognitoAuthorizer
        Namespace: !Ref Namespace
        ApiVersionResource: !Ref ApiVersionResource

Outputs:
  ApiGatewayID:
    Description: ID of the API Gateway
    Value: !Ref APIGateway
    Export:
      Name: !Join [':', [!Ref Namespace, 'APIGateway']]
